_target_: dagnosis.conformal.conformal_predictor.CQR
scale: false
seed: ${random_seed}
cal_size: ${cal_train_ratio}
n_search: 100
param_bounds:
  num_leaves:
    low: 10
    high: 50
  max_depth:
    low: 3
    high: 20
  n_estimators:
    low: 50
    high: 300
  learning_rate:
    low: 0
    high: 1
n_splits: 5